# Day Objectives

## Data Manipulation with NumPy

* Math

* Random

* Filtering

* Statistics

* Aggregation

* Saving Data



In [1]:
import numpy as np

In [4]:
# Create one 2_D array using list
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("shape",arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
shape (2, 3)
2


## Math

In [6]:
li = [1,2,3,4,5,6]
li*2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [5]:
ar = arr+2
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [9]:
arr%2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [10]:
arr//2

array([[0, 1, 1],
       [2, 2, 3]], dtype=int32)

In [12]:
ar4 = np.power(arr,2)
type(ar4)

numpy.ndarray

In [13]:
str(ar4)  # ndarray to str --- convertion of datatype is called type casting

'[[ 1  4  9]\n [16 25 36]]'

In [14]:
# square root of array
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [15]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [16]:
# expo of 2
np.exp2(arr)

array([[ 2.,  4.,  8.],
       [16., 32., 64.]])

In [17]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [18]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [19]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

## Random

In [20]:
import random

In [30]:
ar = np.random.randint(10,100)
ar

14

In [31]:
ar2 = np.random.randint(1,100,5)  # syntax : (low,high,shape)
ar2

array([29, 45, 29, 24, 73])

In [34]:
ar2 = np.random.randint(1,100,(3,3))  # syntax : (low,high,shape)
ar2

array([[28, 83, 66],
       [25, 93, 12],
       [79, 16, 79]])

In [40]:
# generate 6-digit OTP
a=np.random.randint(100000,999999)
a
# 100001

370983

In [47]:
ar=np.random.randint(0,10,6)
list(ar)
int("".join(map(str,list(ar))))

971720

In [48]:
np.random.uniform()

0.21225641096696723

In [52]:
np.random.uniform(1,5)

1.8869397416917817

In [54]:
np.random.randint(1,100,(5,5))

array([[92, 96, 46, 92, 30],
       [44, 92,  1, 16, 66],
       [ 3, 86, 35, 14, 32],
       [10, 29, 24, 50, 40],
       [85, 61, 74, 76,  3]])

In [53]:
np.random.uniform(1,100,(5,5))

array([[67.32481652, 20.02536729, 11.08745493,  2.76429347, 52.86352789],
       [40.63342144, 21.24309155, 95.92200285, 13.50433622, 74.15452445],
       [68.1045122 , 20.17970251, 54.75802761,  6.59521539, 56.3143487 ],
       [ 7.39266449, 36.61497267, 64.71319282, 92.44180707, 36.29887165],
       [99.80378433, 89.70815811, 99.50142375, 61.2167293 , 59.86003618]])

In [58]:
name = ["chaitanya","siva","lakshmi","sireesha","kusuma"]
np.random.choice(name)

'siva'

In [59]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

# Filtering

In [63]:
# create 3,3 2_d array 
ag=np.random.randint(-100,100,[3,3])
ag.ndim
ag.shape
ag

array([[ 88,  94,  70],
       [ 47, -37,   1],
       [-10, -85,  77]])

In [64]:
ag > 0

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [65]:
ag < 0

array([[False, False, False],
       [False,  True, False],
       [ True,  True, False]])

In [66]:
ag >= 35

array([[ True,  True,  True],
       [ True, False, False],
       [False, False,  True]])

In [67]:
ag == 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [68]:
ag != 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [69]:
ag2 = np.array([[1,3,2],[0,7,6],[0,4,5]])
ag2

array([[1, 3, 2],
       [0, 7, 6],
       [0, 4, 5]])

In [70]:
ag2 != 0

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [73]:
ag2 == 0

array([[False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [75]:
ag2 > 3

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [76]:
ag2[ag2 > 3]

array([7, 6, 4, 5])

In [78]:
ag2[ag2 != 0]

array([1, 3, 2, 7, 6, 4, 5])

In [79]:
ag[ag != 0]

array([ 88,  94,  70,  47, -37,   1, -10, -85,  77])

In [84]:
print(ag)
ag[~(ag != 0 )]

[[ 88  94  70]
 [ 47 -37   1]
 [-10 -85  77]]


array([], dtype=int32)

In [83]:
print(ag2)
ag2[~(ag2 != 0)]

[[1 3 2]
 [0 7 6]
 [0 4 5]]


array([0, 0])

In [86]:
ag2 > 0 | ag2 < 5

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [96]:
# nan --- not a number
ag3 = np.array([[1,34,45],[np.nan,67,45],[56,np.nan,678]])
ag3

array([[  1.,  34.,  45.],
       [ nan,  67.,  45.],
       [ 56.,  nan, 678.]])

In [93]:
ag3*3

array([[   3.,  102.,  135.],
       [  nan,  201.,  135.],
       [ 168.,   nan, 2034.]])

In [98]:
#ag3[1][0] = 123
ag3[2:,1:2] =13
ag3

array([[  1.,  34.,  45.],
       [ nan,  67.,  45.],
       [ 56.,  13., 678.]])

In [182]:
ag3

array([[  1.,  34.,  45.],
       [ nan,  67.,  45.],
       [ 56.,  13., 678.]])

In [184]:
ag3[1:2,0:1] = 100
ag3

array([[  1.,  34.,  45.],
       [100.,  67.,  45.],
       [ 56.,  13., 678.]])

In [90]:
np.isnan(ag3)

array([[False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [92]:
ag3[~(np.isnan(ag3))]

array([  1.,  34.,  45.,  67.,  45.,  56., 678.])

In [99]:
ag4 = np.array([0,4,56,67,4,4,34])
np.where(ag4 == 56)  # returns index position

(array([2], dtype=int64),)

In [100]:
ag

array([[ 88,  94,  70],
       [ 47, -37,   1],
       [-10, -85,  77]])

In [101]:
ag > 0

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [108]:
print(arr)
np.any(arr > 0) 
# Logical OR operation -- even one of the element in the array meets the given condition
# it return True when only one condition is saticified else False

[[1 2 3]
 [4 5 6]]


True

In [103]:
np.all(arr > 0)
# Logical AND operation

True

In [104]:
ag2

array([[1, 3, 2],
       [0, 7, 6],
       [0, 4, 5]])

In [105]:
np.any(ag2 > 0)

True

In [106]:
np.all(ag2 > 0)

False

## Statistics / Analysis

In [109]:
ar

array([9, 7, 1, 7, 2, 0])

In [110]:
ar.min()

0

In [111]:
ar.max()

9

In [112]:
ar.mean()

4.333333333333333

In [114]:
np.median(ar)

4.5

In [115]:
np.std(ar)

3.4480268109295333

In [117]:
np.var(arr) # variance

2.9166666666666665

In [118]:
ag2

array([[1, 3, 2],
       [0, 7, 6],
       [0, 4, 5]])

In [119]:
np.median(arr)

3.5

In [122]:
np.median(ag2,axis=1)  # column

array([2., 6., 4.])

In [123]:
np.median(ag2, axis =0)  # row 

array([0., 4., 5.])

# Aggregation

In [124]:
ag2

array([[1, 3, 2],
       [0, 7, 6],
       [0, 4, 5]])

In [125]:
np.sum(ag2)  # it returns overall summation

28

In [126]:
np.sum(ag2,axis =0) # it returns sum of indivival rows\

array([ 1, 14, 13])

In [128]:
np.sum(ag2,axis =1)

array([ 6, 13,  9])

In [129]:
# Concatenation
ag2

array([[1, 3, 2],
       [0, 7, 6],
       [0, 4, 5]])

In [134]:
np.concatenate([ag2,ag2],axis = 0) # it default it concat in rows

array([[1, 3, 2],
       [0, 7, 6],
       [0, 4, 5],
       [1, 3, 2],
       [0, 7, 6],
       [0, 4, 5]])

In [136]:
data = np.concatenate([ag2,ag2],axis = 1)
data 

array([[1, 3, 2, 1, 3, 2],
       [0, 7, 6, 0, 7, 6],
       [0, 4, 5, 0, 4, 5]])

# Saving Data

In [137]:
np.save("array",data) # np.save(path,array)

In [139]:
np.save("data_array.npy",data)

In [142]:
np.load("data_array.npy")

array([[1, 3, 2, 1, 3, 2],
       [0, 7, 6, 0, 7, 6],
       [0, 4, 5, 0, 4, 5]])

In [143]:
data

array([[1, 3, 2, 1, 3, 2],
       [0, 7, 6, 0, 7, 6],
       [0, 4, 5, 0, 4, 5]])

In [147]:
data[0:1,1:2] = 300

In [148]:
data

array([[  1, 300,   2,   1,   3,   2],
       [  0,   7,   6,   0,   7,   6],
       [  0,   4,   5,   0,   4,   5]])

In [ ]:
# Task
# Create this array by using numpy methods

1 1 1 1 1
1 1 0 0 1
1 0 1 0 1
1 0 0 1 1
1 1 1 1 1

In [153]:
fg=np.ones([5,5],dtype = int)
fg[1,2:4]=0
fg[2,3]=0
fg[3,1:3]=0
fg[2,1]=0
print(fg)

[[1 1 1 1 1]
 [1 1 0 0 1]
 [1 0 1 0 1]
 [1 0 0 1 1]
 [1 1 1 1 1]]


In [168]:
task = np.eye(5,dtype= int)
task[[0,-1]] = 1
task[:,0:1] = 1
task[:,-1] = 1
task

array([[1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]])

In [160]:
task[[0,-1]] = 1
task

array([[1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1]])

In [167]:
task[:,0:1] = 1
task[:,-1] = 1
task

array([[1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]])

# Pandas 
* It is an excellent tool for processing and analyzing real world data
* [Pandas_website](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html#user-guide)

* Which is a build in Library and using Pandas heavily for data manipulation, visualisation, building machine learning models, etc.
* There are two main data structures in Pandas - Series and Dataframes

### The Pandas Series (similar to a numpy array)

* A dataframe is simply a table where each column is a pandas series. 
    * Creating a pandas series
    * Indexing series
    
    




### Dataframes
* It is a table with rows and columns, with rows having an index and columns having meaningful names.

id |col1 | col2
--|--|--
1|abc|xyz
2|123|345
3|454|jhg

In [169]:
import pandas as pd

In [170]:
# create pandas series using list
se = pd.Series([1,232,44,545,55,66,7])
se

0      1
1    232
2     44
3    545
4     55
5     66
6      7
dtype: int64

In [172]:
se2 = pd.Series([1,232,44,545,"dsgsfd","dhgfjdgs",7.4])
se2

0           1
1         232
2          44
3         545
4      dsgsfd
5    dhgfjdgs
6         7.4
dtype: object

In [174]:
# Explicitly specifying indice
se2 = pd.Series([1,232,44,545,"dsgsfd","dhgfjdgs",7.4],index= ["a","b","c",345,"g",76.87,"y"])
se2

a               1
b             232
c              44
345           545
g          dsgsfd
76.87    dhgfjdgs
y             7.4
dtype: object

In [175]:
date = pd.date_range(start = "2020-08-03",end = "2020-08-12")
date

DatetimeIndex(['2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06',
               '2020-08-07', '2020-08-08', '2020-08-09', '2020-08-10',
               '2020-08-11', '2020-08-12'],
              dtype='datetime64[ns]', freq='D')

In [177]:
import math

import random

import calendar

import datetime

import time

In [180]:
print(calendar.calendar(2020))

                                  2020

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                         1
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       2  3  4  5  6  7  8
13 14 15 16 17 18 19      10 11 12 13 14 15 16       9 10 11 12 13 14 15
20 21 22 23 24 25 26      17 18 19 20 21 22 23      16 17 18 19 20 21 22
27 28 29 30 31            24 25 26 27 28 29         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 

In [181]:
print(calendar.calendar(2020,11))

                                                                                                                                 2020

                                      January                                                                                  February                                                                                  March
   Monday     Tuesday    Wednesday    Thursday     Friday     Saturday     Sunday           Monday     Tuesday    Wednesday    Thursday     Friday     Saturday     Sunday           Monday     Tuesday    Wednesday    Thursday     Friday     Saturday     Sunday
                              1           2           3           4           5                                                                            1           2                                                                                        1
      6           7           8           9          10          11          12                3           4           5    

In [ ]:
dir()
help()