## Numpy

- Statistical Functions

In [5]:
import numpy as np

In [6]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [7]:
arr.sum()

100

In [8]:
arr1 = np.array([[0,10,20],[20,45,67],[23,45,67]])
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [9]:
arr1.sum()

297

In [10]:
arr1.sum(axis=0)

array([ 43, 100, 154])

In [11]:
arr1.sum(axis=1)

array([ 30, 132, 135])

In [12]:
arr1.sum(0)

array([ 43, 100, 154])

In [13]:
## average
print(np.average(arr))
print(np.average(arr1))

25.0
33.0


In [14]:
np.average(arr,axis=0)

25.0

In [15]:
np.average(arr,0)

25.0

In [16]:
# product
np.prod(arr)

240000

In [17]:
arr

array([10, 20, 30, 40])

In [18]:
np.prod(arr1)

0

In [19]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [20]:
np.prod(arr1,0)

array([    0, 20250, 89780])

In [21]:
np.prod(arr1,axis=1)

array([    0, 60300, 69345])

In [22]:
# minimum
print(arr.min())
print(arr1.min())

10
0


In [23]:
arr1.min(1)

array([ 0, 20, 23])

In [24]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [25]:
arr1.min(0)

array([ 0, 10, 20])

In [26]:
# maximum
arr.max()

40

In [27]:
arr1.max()

67

In [28]:
arr1.max(0)

array([23, 45, 67])

In [29]:
# mean
arr.mean()

25.0

In [30]:
arr1.mean(1)

array([10., 44., 45.])

In [35]:
# median
np.median(arr1)

23.0

In [37]:
np.median(arr1,0)

array([20., 45., 67.])

In [39]:
from statistics import mode

In [41]:
help(mode)

Help on function mode in module statistics:

mode(data)
    Return the most common data point from discrete or nominal data.
    
    ``mode`` assumes discrete data, and returns a single value. This is the
    standard treatment of the mode as commonly taught in schools:
    
    >>> mode([1, 1, 2, 3, 3, 3, 3, 4])
    3
    
    This also works with nominal (non-numeric) data:
    
    >>> mode(["red", "blue", "blue", "red", "green", "red", "red"])
    'red'
    
    If there is not exactly one most common value, ``mode`` will raise
    StatisticsError.



In [114]:
mode([1, 1, 2, 3, 3, 3, 3, 4,4,4])

3

In [45]:
# numpy var
#(item1-mean)2+(item2-mean)2+....+(itemn-mean)2
arr1.var()

517.3333333333334

In [46]:
# std deviation
arr.std()

11.180339887498949

In [47]:
arr1.std()

22.744962812309307

In [48]:
#cumsum
arr

array([10, 20, 30, 40])

In [49]:
arr.cumsum()

array([ 10,  30,  60, 100], dtype=int32)

In [50]:
arr1.cumsum(1)

array([[  0,  10,  30],
       [ 20,  65, 132],
       [ 23,  68, 135]], dtype=int32)

In [51]:
#cumprod
arr.cumprod()

array([    10,    200,   6000, 240000], dtype=int32)

- Aggregation

In [52]:
arr

array([10, 20, 30, 40])

In [53]:
arr.argmin() # index

0

In [54]:
arr[arr.argmin()]

10

In [55]:
arr1.argmin(1)

array([0, 0, 0], dtype=int64)

In [56]:
arr1.argmin(0)

array([0, 0, 0], dtype=int64)

In [58]:
arr[1]

20

In [64]:
arr1.argmin()

0

In [65]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [70]:
result = np.where(arr == 40) # to findout the index for particular value
result

(array([3], dtype=int64),)

In [69]:
arr

array([10, 20, 30, 40])

In [74]:
print(arr1.argmin())

0


In [79]:
arr1[0]

array([ 0, 10, 20])

In [78]:
arr1[0][1]

10

In [80]:
arr1[1]

array([20, 45, 67])

In [81]:
arr1[1][0]

20

In [72]:
arr1

array([[ 0, 10, 20],
       [20, 45, 67],
       [23, 45, 67]])

In [73]:
arr1.argmin(1)

array([0, 0, 0], dtype=int64)

In [82]:
# correlation coefficient
np.corrcoef(arr)

1.0

In [83]:
np.corrcoef(arr1)

array([[1.        , 0.99932165, 1.        ],
       [0.99932165, 1.        , 0.99932165],
       [1.        , 0.99932165, 1.        ]])

### Filtering

In [84]:
arr2 = np.arange(110)

In [85]:
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109])

In [86]:
arr2[0]

0

In [87]:
arr2[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr2[1:10:2]

array([1, 3, 5, 7, 9])

In [89]:
arr2[-20:]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109])

In [91]:
a = np.arange(100)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [102]:
arr[arr>10]

array([20, 30, 40])

In [95]:
iter = (x*x for x in range(5) for y in range(10) if y<x)
np.fromiter(iter,float)

array([ 1.,  4.,  4.,  9.,  9.,  9., 16., 16., 16., 16.])

- np.fromiter(iterable,dtype)
- (output loops condition)

In [96]:
arr

array([10, 20, 30, 40])

In [100]:
np.where(arr>20)

(array([2, 3], dtype=int64),)

In [101]:
arr[np.where(arr>20)]

array([30, 40])

In [103]:
np.nonzero(arr>20)

(array([2, 3], dtype=int64),)

In [105]:
arr[np.nonzero(arr>20)]

array([30, 40])

In [106]:
arr3 = np.array([10,10,20,30,10])
arr3

array([10, 10, 20, 30, 10])

In [107]:
np.count_nonzero(arr3==10)

3

- Saving data

In [108]:
data = np.linspace(0,100,50)
data

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [109]:
np.savetxt("sample_data",data)

In [110]:
x = np.linspace(0,1,201)
y = np.random.random(201)
np.savetxt("sample",[x,y])

In [111]:
header = "x-col,y-col"
np.savetxt("sample1",[x,y],header=header)

- load

In [112]:
np.loadtxt("sample")

array([[0.00000000e+00, 5.00000000e-03, 1.00000000e-02, 1.50000000e-02,
        2.00000000e-02, 2.50000000e-02, 3.00000000e-02, 3.50000000e-02,
        4.00000000e-02, 4.50000000e-02, 5.00000000e-02, 5.50000000e-02,
        6.00000000e-02, 6.50000000e-02, 7.00000000e-02, 7.50000000e-02,
        8.00000000e-02, 8.50000000e-02, 9.00000000e-02, 9.50000000e-02,
        1.00000000e-01, 1.05000000e-01, 1.10000000e-01, 1.15000000e-01,
        1.20000000e-01, 1.25000000e-01, 1.30000000e-01, 1.35000000e-01,
        1.40000000e-01, 1.45000000e-01, 1.50000000e-01, 1.55000000e-01,
        1.60000000e-01, 1.65000000e-01, 1.70000000e-01, 1.75000000e-01,
        1.80000000e-01, 1.85000000e-01, 1.90000000e-01, 1.95000000e-01,
        2.00000000e-01, 2.05000000e-01, 2.10000000e-01, 2.15000000e-01,
        2.20000000e-01, 2.25000000e-01, 2.30000000e-01, 2.35000000e-01,
        2.40000000e-01, 2.45000000e-01, 2.50000000e-01, 2.55000000e-01,
        2.60000000e-01, 2.65000000e-01, 2.70000000e-01, 2.750000