# Numpy

- Numerical python,popularly known as numpy has been designed to carry out mathematical computations at faster and easier rate
- Numpy provides a large library of high level mathematical functions to operate on these structures.
- Data structures like multi dimensional arrays beyond materices and linear arrys

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

In [5]:
arr = np.array([1,2,3])
type(arr)

numpy.ndarray

In [6]:
arr.ndim

1

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr1 = np.array([1,2,2.3,"apssdc"])
arr1.dtype

dtype('<U32')

In [9]:
np.array("04-08-2020")

array('04-08-2020', dtype='<U10')

- 'b' - boolean
- 'i' - signed integer
- 'u' - unsigned integer
- 'f' - float
- 'c' - complex
- 'U' - unicode
- 'O' - objects

In [11]:
s = np.array(4+5j)
s.dtype

dtype('complex128')

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
range(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [15]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [16]:
f = np.arange(1,51)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [20]:
f.shape

(50,)

In [18]:
d = f.reshape(5,10)
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [19]:
d.shape

(5, 10)

In [21]:
d.ndim

2

In [22]:
f.reshape(5,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
f.reshape(-1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [24]:
f.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [25]:
f.reshape(4,10)

ValueError: cannot reshape array of size 50 into shape (4,10)

In [26]:
arr4 = np.arange(0,50).reshape(5,1,10)
arr4

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])

In [32]:
arr4[1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
arr4[3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [27]:
arr4.ndim

3

In [28]:
arr4.shape

(5, 1, 10)

In [29]:
arr4.dtype

dtype('int32')

In [34]:
np.arange(0,100).reshape(10,1,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [36]:
np.arange(0,100).reshape(2,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [37]:
arr3d=np.arange(0,40).reshape(2,2,10)
arr3d


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]])

In [38]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [39]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [40]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [41]:
np.ones(2)

array([1., 1.])

In [42]:
np.ones(2,dtype=int)

array([1, 1])

In [43]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros((3,3),dtype=object)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

In [48]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

#### Adding and Sorting elements

In [61]:
a = np.array([12,1,2,45,90.4,90.4])
a

array([12. ,  1. ,  2. , 45. , 90.4, 90.4])

In [52]:
np.sort(a)

array([ 1. ,  2. , 12. , 45. , 90.4])

In [62]:
-np.sort(-a)

array([90.4, 90.4, 45. , 12. ,  2. ,  1. ])

In [53]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind='quicksort', order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be used, in the order in which
        they come up in the dtype, to break ties.
    
    Returns
    -------
    sorted_array : ndarray
        Array of the same type and shape as `a`.
    
    S

In [56]:
surnames = ("rowdy","pinsetti","purple")
first_names = ("archana","alekhya","mounika")
ind = np.lexsort((first_names,surnames))
ind

array([1, 2, 0], dtype=int64)

In [57]:
[surnames[i]+" "+first_names[i] for i in ind ]

['pinsetti alekhya', 'purple mounika', 'rowdy archana']

In [58]:
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis
   

array([[1, 4],
       [1, 3]])

In [59]:
np.sort(a,axis=0)

array([[1, 1],
       [3, 4]])

In [60]:
np.sort(a,axis=1)

array([[1, 4],
       [1, 3]])

In [63]:
a

array([12. ,  1. ,  2. , 45. , 90.4, 90.4])

In [67]:
np.partition(a,4)

array([ 1. ,  2. , 12. , 45. , 90.4, 90.4])

In [72]:
a = np.array([3,4,2,1,34,6,17,45,22,78])
np.partition(a,2)

array([ 1,  2,  3,  4, 34,  6, 17, 45, 22, 78])

In [75]:
a = np.array([1,2,3,4])
b = np.array([3,23,2,1])
np.concatenate((a,b))

array([ 1,  2,  3,  4,  3, 23,  2,  1])

### Masking

In [77]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a[a%2==0]

array([2, 4, 6, 8])

In [80]:
c = a[(a>3) & (a<7)]
print("between 3 & 4",c)

between 3 & 4 [4 5 6]


In [81]:
c = a[(a>5) | (a==5)]
print(c)

[5 6 7 8 9]


### Indexing

In [82]:
f = np.arange(1,100,2)

In [83]:
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [84]:
f[1:20]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])

In [85]:
f[8]

17

In [86]:
f[::-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [87]:
f[-10::]

array([81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [88]:
f[-10:-2]

array([81, 83, 85, 87, 89, 91, 93, 95])

#### Mathematical Functions

#### Arithmetic functions

In [89]:
a = np.array([1,2,3])
b = np.array([23,12,45])
print(a+b)

[24 14 48]


In [90]:
print(a-b)

[-22 -10 -42]


In [91]:
print(a/b)

[0.04347826 0.16666667 0.06666667]


In [94]:
print(a%b)

[1 2 3]


In [93]:
np.divmod(b,a)

(array([23,  6, 15], dtype=int32), array([0, 0, 0], dtype=int32))

In [95]:
np.divide(a,b)

array([0.04347826, 0.16666667, 0.06666667])

In [96]:
np.remainder(a,b)

array([1, 2, 3], dtype=int32)

In [97]:
a.sum()

6

In [98]:
b.sum()

80

In [99]:
a = np.array([[1,2],[5,6]])
a

array([[1, 2],
       [5, 6]])

In [100]:
a.sum()

14

In [101]:
a.sum(axis=0)

array([6, 8])

In [102]:
a.sum(axis=1)

array([ 3, 11])

#### Log & Exp

In [103]:
np.log(2)

0.6931471805599453

In [104]:
a 

array([[1, 2],
       [5, 6]])

In [105]:
np.log(a)

array([[0.        , 0.69314718],
       [1.60943791, 1.79175947]])

In [107]:
np.log10(a)

array([[0.        , 0.30103   ],
       [0.69897   , 0.77815125]])

In [108]:
np.log2(a)

array([[0.        , 1.        ],
       [2.32192809, 2.5849625 ]])

In [110]:
np.exp(a)

array([[  2.71828183,   7.3890561 ],
       [148.4131591 , 403.42879349]])

### Rounding functions

In [114]:
a = np.array([-1.7,2.3,-8.9,6.2])
np.round(a)

array([-2.,  2., -9.,  6.])

In [115]:
np.floor(a)

array([-2.,  2., -9.,  6.])

In [116]:
np.ceil(a)

array([-1.,  3., -8.,  7.])

In [117]:
help(np.round)

Help on function round_ in module numpy:

round_(a, decimals=0, out=None)
    Round an array to the given number of decimals.
    
    See Also
    --------
    around : equivalent function; see for details.



In [118]:
help(np.divmod)

Help on ufunc object:

divmod = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arra

### Random concept

In [119]:
from numpy import random

In [121]:
random.randint(100)

60

In [122]:
random.rand() # generate a roandom float number from 0 to 1

0.23004189892545035

In [123]:
random.rand()

0.6287141461011587

In [124]:
random.rand(10)

array([0.97402743, 0.90598117, 0.64411646, 0.47507975, 0.45699635,
       0.07710101, 0.45089868, 0.72976478, 0.74697909, 0.54350159])

In [125]:
random.randint(100,size=10)

array([54, 33, 34, 69, 29, 58, 37, 85, 85, 87])

In [127]:
random.choice(["a","b","k","l"])

'b'

In [137]:
random.choice(["alekhya","mounika","gireesha","archana"],p=[0.2,0.1,0.4,0.3],size=(100))

array(['alekhya', 'archana', 'gireesha', 'archana', 'archana', 'gireesha',
       'archana', 'gireesha', 'alekhya', 'gireesha', 'gireesha',
       'archana', 'archana', 'gireesha', 'archana', 'gireesha',
       'gireesha', 'archana', 'alekhya', 'archana', 'gireesha', 'mounika',
       'archana', 'archana', 'gireesha', 'archana', 'archana', 'mounika',
       'alekhya', 'alekhya', 'archana', 'alekhya', 'alekhya', 'gireesha',
       'gireesha', 'alekhya', 'archana', 'alekhya', 'archana', 'gireesha',
       'alekhya', 'archana', 'gireesha', 'gireesha', 'gireesha',
       'mounika', 'archana', 'alekhya', 'gireesha', 'gireesha',
       'gireesha', 'alekhya', 'gireesha', 'alekhya', 'archana', 'archana',
       'alekhya', 'gireesha', 'mounika', 'alekhya', 'alekhya', 'gireesha',
       'gireesha', 'gireesha', 'alekhya', 'gireesha', 'mounika',
       'archana', 'mounika', 'mounika', 'gireesha', 'alekhya', 'archana',
       'alekhya', 'alekhya', 'gireesha', 'gireesha', 'gireesha',
       'mounika

In [133]:
a 

array([-1.7,  2.3, -8.9,  6.2])

In [134]:
np.count(a,2.3)

AttributeError: module 'numpy' has no attribute 'count'