### Numpy:


* Numpy is abbrivated as Numerical Python.
* Numpy is mainly used to create arrrays.
    * 1-d
    * 2-d
    * 3-d
    * Mutli Dimensional.
    
#### Why Numpy?

* Arrays occupy very less memory space when compared lists.
* Arrays will take very less execution time when compared lists.
* Numpy is used to deal with all MachineLearning,Datascience concepts very easily and effectively.


In [3]:
import numpy as np ### importing numpy library


#### Creating array:



In [9]:
a1 = np.array([1.0,2,3,4,'a'])  ### 1-d array
a1

array(['1.0', '2', '3', '4', 'a'], dtype='<U32')

In [10]:
a1.dtype   ### checking the datatype of the array elements.

dtype('<U32')

In [11]:
a1 = np.append(a1,[12,14])   ### adding elements to the existing array 
a1

array(['1.0', '2', '3', '4', 'a', '12', '14'], dtype='<U32')

In [12]:
a = np.arange(0,10)   ### array within a range
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.arange(0,10,2) ### range with step value
a

array([0, 2, 4, 6, 8])

In [15]:
a.nbytes   ## to check the memory space ocupied.

20

In [17]:
a.itemsize ## individual element size.


4

In [19]:
len(a) ## length of the array

5

In [21]:
np.linspace(1,10,20)  ### dividing the given range with equal difference between each element.

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
np.full(10,"Python")  ## repeating the same value for defined count

array(['Python', 'Python', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Python'], dtype='<U6')

In [23]:
np.ones(10)  ### getting all i's in the array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [29]:
np.full(10,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [31]:
### 1-d array:

a1 = np.array([1,2,3,4])
a1


array([1, 2, 3, 4])

In [33]:
### 2-d array:   combination more 1-d arrays

a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
### 3-d array:  combination of more 2-d arrays

a3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,8,7,6],[1,2,3,4]]])
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [1, 2, 3, 4]]])

In [36]:
a1.ndim  ### to check dimansion of the array

1

In [37]:
a2.ndim

2

In [38]:
a3.ndim

3

In [47]:
### Mutlidimensional array:

am = np.array([1,2,3,4],ndmin = 5)
am

array([[[[[1, 2, 3, 4]]]]])

In [50]:
am1 = np.array([[1,2,3,4],[5,6,7,8]],ndmin = 5)
am1

array([[[[[1, 2, 3, 4],
          [5, 6, 7, 8]]]]])

### accessing elements from the array:



In [54]:
# accessing elements from 1-d array:

a1

array([1, 2, 3, 4])

In [52]:
a1[-1]

4

In [53]:
a1[2]

3

In [55]:
a1[1:3]

array([2, 3])

In [62]:
# accessing elements from 2-d array:

a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
a2[0]

array([1, 2, 3, 4])

In [58]:
a2[-1]

array([5, 6, 7, 8])

In [60]:
a2[0,2]

3

In [61]:
a2[1,-1]

8

In [63]:
a2[:,-1]

array([4, 8])

In [64]:
a2[:,1:3]

array([[2, 3],
       [6, 7]])

In [65]:
a2[:,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [67]:
a = np.array([[1,2,2],[3,4,5],[5,6,7]])
a

array([[1, 2, 2],
       [3, 4, 5],
       [5, 6, 7]])

In [68]:
a[1:,1:]

array([[4, 5],
       [6, 7]])

In [69]:
### accessing elements from 3-d array:

a3  

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [1, 2, 3, 4]]])

In [70]:
a3[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
a3[1]

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [72]:
a3[0,0]

array([1, 2, 3, 4])

In [73]:
a3[1,0]

array([9, 8, 7, 6])

In [75]:
a3[0,0,2:]

array([3, 4])

In [76]:
a3[1,1,2:]

array([3, 4])

In [77]:
a3[:,:,2:]

array([[[3, 4],
        [7, 8]],

       [[7, 6],
        [3, 4]]])

In [78]:
a3[0:2,0:1,2:4]


array([[[3, 4]],

       [[7, 6]]])

In [81]:
### shape of the array:

a = np.array([[1,2,3,4],[5,6,7,8]])
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
a.shape

(2, 4)

In [82]:
a1 

array([1, 2, 3, 4])

In [83]:
a1.shape

(4,)

In [84]:

a3.shape

(2, 2, 4)

In [85]:
a3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [1, 2, 3, 4]]])

In [91]:
### reshape of the array:

## note : total length of the array should be even ,then only reshape will be applied.

a = np.array([1,2,3,4,5,6,7])

a

array([1, 2, 3, 4, 5, 6, 7])

In [94]:
a.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [90]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
a.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [108]:
b = np.arange(1,8)
b

array([1, 2, 3, 4, 5, 6, 7])

In [109]:
b.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [110]:
b.reshape(1,7)

array([[1, 2, 3, 4, 5, 6, 7]])